/**
 * English version of the 14 Socionics relationship definitions.
 *
 * Structure mirrors compatibility.ts but with English content.
 * COMPATIBILITY_MAP and helper functions remain in the original file
 * since they use type codes (not translatable text).
 */

import type { RelationType, RelationDefinition } from './compatibility';

export const RELATION_DEFINITIONS_EN: Record<RelationType, RelationDefinition> = {
    Dual: {
        type: 'Dual',
        name: 'Dual',
        nameEn: 'Dual',
        stars: 5,
        emoji: '💎',
        summary: 'The best match. Ideal partners who naturally complement each other\'s weaknesses.',
        overview: 'The Dual relationship is considered the most ideal in Socionics. Each person\'s strengths naturally compensate for the other\'s weaknesses, creating an effortless sense of security just by being together.\n\nYou understand each other\'s needs without words and support each other without strain — a remarkably rare pairing. The longer you\'re together, the more this relationship reveals its true value.',
        strengths: [
            'Complement each other\'s weaknesses unconsciously',
            'Feel naturally relaxed and authentic together',
            'Rarely tire of each other even over long periods',
        ],
        cautions: [
            'May not recognize each other\'s strengths at first meeting',
            'The many differences can be disorienting initially',
            'Risk of becoming overly dependent on each other',
        ],
        workCompatibility: {
            teamDynamics: 'The ultimate tag team. One naturally strategizes while the other executes — an ideal division of labor that elevates the entire team\'s performance.',
            roleAdvice: 'Clarify each other\'s expertise and divide responsibilities. One handles the front end while the other supports the back office — this arrangement maximizes efficiency.',
            frictionPoint: 'Leaving everything to each other can lead to communication gaps. Make a habit of regular check-ins to keep alignment.',
        },
        loveCompatibility: {
            attraction: 'Drawn together by a hard-to-articulate sense of calm: "I feel strangely at peace with this person." Less drama, but deep trust develops.',
            challenge: 'Because your partner covers your weaknesses so effortlessly, you may forget to notice or appreciate their contribution. Don\'t take it for granted.',
            longevityTip: 'Build a monthly habit of expressing gratitude to each other. "Thank you" is the strongest adhesive.',
        },
        dos: [
            'Respect your partner\'s strengths and fully delegate their domain',
            'Show your weaknesses honestly and accept help',
            'Regularly express gratitude in words',
        ],
        donts: [
            'Take your partner\'s contributions for granted',
            'Force your methods on the other person',
            'Criticize your partner\'s weaknesses (your strength IS their weakness)',
        ],
        concreteTip: 'Example: When the logical ILE analyzes "The risks of this plan are…", the sensory SEI responds "Then let\'s actually try it." A natural ideation → execution flow emerges between them, dramatically boosting team productivity.',
        faq: [
            { question: 'Why is the Dual relationship the best match?', answer: 'In Dual relations, each person\'s leading function naturally compensates the other\'s weakest 4th function. Weaknesses are covered without conscious effort, creating a stress-free, secure bond.' },
            { question: 'Do Duals click immediately?', answer: 'Actually, the chemistry is often hard to notice at first. Duality\'s true value shows in longer-term relationships. Even if your initial impression is "this person seems different," the comfort grows as you spend more time together.' },
        ],
    },
    Activity: {
        type: 'Activity',
        name: 'Activity',
        nameEn: 'Activity',
        stars: 4,
        emoji: '⚡',
        summary: 'Energizing and stimulating — you spark each other\'s motivation.',
        overview: 'The Activity relationship doubles your energy when you\'re together. Each person\'s ideas and actions ignite the other, producing insights neither would reach alone.\n\nHowever, that high intensity means prolonged togetherness can lead to fatigue. Maintaining a healthy distance is the key to maximizing this relationship.',
        strengths: [
            'Mutually boost motivation and energy',
            'Conversations flow easily and spark new ideas',
            'Rarely falls into monotony — always lively',
        ],
        cautions: [
            'Too much stimulation leads to mutual exhaustion',
            'Slight timing mismatches can cause friction',
            'May stay at a surface-level fun without deeper understanding',
        ],
        workCompatibility: {
            teamDynamics: 'Explosive results in brainstorming and kickoff meetings. Your exchanges spark innovation and generate groundbreaking ideas.',
            roleAdvice: 'Best paired during project launch and planning phases. Routine work reduces stimulation and may lower both partners\' performance.',
            frictionPoint: 'Subtle differences in pace can cause progress to go out of sync. Set clear milestones and check in regularly.',
        },
        loveCompatibility: {
            attraction: 'From the moment you meet, conversation flows and you instantly feel "This person is so fun to be around!" Every date brings fresh discoveries.',
            challenge: 'Spending too much time together drains your batteries. Without alone time, you risk burning out.',
            longevityTip: 'Set aside one "solo day" per week to recharge your individual energy.',
        },
        dos: [
            'Ride each other\'s ideas and raise the energy together',
            'Share hobbies and activities that stimulate both of you',
            'Maintain healthy distance and respect alone time',
        ],
        donts: [
            'Force non-stop togetherness',
            'Over-adapt to your partner\'s pace at your own expense',
            'Become dissatisfied when the initial spark fades',
        ],
        concreteTip: 'Example: You hit it off instantly at a social event. "Let\'s do this next!" "That\'s amazing!" — your energy feeds off each other and sweeps everyone around you along. But the next day, you\'re both completely drained.',
        faq: [
            { question: 'What\'s the difference between Activity and Dual?', answer: 'If Dual is "quiet security," Activity is "explosive stimulation." Duals are stable long-term, while Activity pairs produce bursts of energy but can exhaust each other over extended periods.' },
            { question: 'How do Activity partners last long-term?', answer: 'Healthy distance is your greatest weapon. Rather than daily togetherness, meet periodically when you\'re both recharged — every reunion will feel fresh and exciting.' },
        ],
    },
    Mirror: {
        type: 'Mirror',
        name: 'Mirror',
        nameEn: 'Mirror',
        stars: 4,
        emoji: '🪞',
        summary: 'Similar thinking but different approaches — great for constructive debate.',
        overview: 'The Mirror relationship pairs people who share interests but take different approaches. Like looking into a mirror, each reveals perspectives the other hadn\'t noticed.\n\nDiscussions tend to be highly constructive and promote intellectual growth. However, there\'s an occasional frustration of "we almost understand each other, but something\'s slightly off."',
        strengths: [
            'Enables deep, constructive discussions',
            'Learn from each other\'s viewpoints and grow intellectually',
            'Shared interests mean conversations never run dry',
        ],
        cautions: [
            'Frustrating near-misses in understanding',
            'Both may insist "I\'m right" in debates',
            'Weak behavioral complementarity',
        ],
        workCompatibility: {
            teamDynamics: 'Ideal sparring partners for ideas. You share the same problem awareness but propose solutions from different angles, producing high-quality output.',
            roleAdvice: 'Best when working on parallel domains within the same project and reviewing each other\'s work regularly.',
            frictionPoint: 'When methods clash, neither backs down. Establish ground rules: let data and results be the judge.',
        },
        loveCompatibility: {
            attraction: '"This person is like me, yet somehow sees things differently" — intellectual curiosity draws you together. Conversations are endlessly engaging.',
            challenge: 'Because you\'re so similar, "Why don\'t you understand THAT?" frustrations build easily.',
            longevityTip: 'Approach each other not as "similar" but as "different individuals." Treat the gaps as fascinating rather than flawed.',
        },
        dos: [
            'Embrace your partner\'s different perspective as "interesting"',
            'Enjoy discussions and incorporate each other\'s ideas',
            'Enlist third parties to cover behavioral gaps',
        ],
        donts: [
            'Turn discussions into win/lose competitions',
            'Dismiss your partner\'s opinions because you\'re "similar"',
            'Reject differences in action patterns',
        ],
        concreteTip: 'Example: Both want to "improve efficiency," but one tackles it through system design while the other focuses on process improvement. "Oh, that approach works too!" — discoveries like this happen daily.',
        faq: [
            { question: 'What exactly is the Mirror relationship?', answer: 'Mirror types share the same Ego functions (leading + creative) but in reverse order. For instance, ILE (Ne-Ti) and LII (Ti-Ne) use the same Ne/Ti, but which function leads is swapped.' },
            { question: 'What if Mirror debates get too heated?', answer: 'Since both tend to believe they\'re right, agree in advance to use objective data or third-party opinions as the deciding factor. This keeps debates healthy and productive.' },
        ],
    },
    Identity: {
        type: 'Identity',
        name: 'Identity',
        nameEn: 'Identity',
        stars: 3,
        emoji: '👥',
        summary: 'Same type, deep understanding — but shared blind spots too.',
        overview: 'The Identity relationship is literally a meeting of the same type. You understand each other\'s thoughts instantly and share deep empathy.\n\nHowever, since your weaknesses are also identical, you can\'t complement each other — and you\'re prone to falling into the same traps together. The relationship may lack stimulation, requiring external sources of growth.',
        strengths: ['Immediate deep empathy and understanding', 'Aligned values with minimal conflict', 'Intuitively grasp each other\'s motivations'],
        cautions: ['Same weaknesses mean no complementation', 'Lack of stimulation and growth opportunities', 'Risk of enabling each other and stagnating'],
        workCompatibility: { teamDynamics: 'Communication costs are extremely low because you read each other perfectly. However, shared blind spots mean the team\'s collective weakness is amplified.', roleAdvice: 'Since you share the same strengths, focus on dividing by sub-specialty rather than competing. Add a third party who covers your joint weak spots.', frictionPoint: 'Rivalry can emerge — "I\'m better at this than you." Choose collaboration over comparison.' },
        loveCompatibility: { attraction: '"This person completely understands me" — you\'re drawn by the security of total understanding. It feels like reconnecting with an old friend from the very first meeting.', challenge: 'Shared weaknesses mean problems can topple you both simultaneously. The lack of novelty makes things go stale quickly.', longevityTip: 'Bring fresh air into your shared world through outside friendships and new hobbies.' },
        dos: ['Empathize deeply and create mutual security', 'Introduce new stimulation through external interactions', 'Together, find allies who complement your shared weaknesses'],
        donts: ['Retreat into a closed two-person bubble', 'Compare each other\'s abilities competitively', 'Assume "they must understand" and neglect communication'],
        concreteTip: 'Example: Working on a presentation together, you\'re both great at the same parts and equally bad at the same parts. Neither can say "you take this" — strengths overlap while weaknesses go unaddressed. Actively invite a complementary third person.',
        faq: [
            { question: 'Are same-type pairs compatible?', answer: 'There\'s deep understanding, but no complementation since you share the same weaknesses. Great as friends, but as work or life partners, you\'ll need external support to avoid getting stuck in the same ruts.' },
        ],
    },
    SemiDual: {
        type: 'SemiDual',
        name: 'Semi-Dual',
        nameEn: 'Semi-Dual',
        stars: 4,
        emoji: '🌗',
        summary: 'Near-Dual complementarity with one blind spot — a "close but not quite" match.',
        overview: 'The Semi-Dual relationship is very close to the ideal Dual. Each person\'s strengths cover most of the other\'s weaknesses, creating a natural complementary bond.\n\nUnlike the perfect Dual, however, one area remains uncovered. Whether you can tolerate that subtle mismatch determines this relationship\'s success.',
        strengths: ['High complementarity close to Dual level', 'Can build a relatively relaxed relationship', 'Easy to leverage each other\'s strengths'],
        cautions: ['One blind spot remains uncovered', 'Expecting perfect complementation leads to disappointment', 'Subtle misalignments can accumulate'],
        workCompatibility: { teamDynamics: 'Strong complementarity makes teamwork highly effective on most fronts. Occasional disagreements in specific areas are to be expected.', roleAdvice: 'Maximize each other\'s strengths while seeking third-party support for the uncovered gap.', frictionPoint: '"We click on almost everything — why not HERE?" Expectation gaps create stress.' },
        loveCompatibility: { attraction: 'An appealing balance of natural comfort and moderate stimulation.', challenge: 'If you expect Dual-level perfection, the "something\'s missing" feeling can nag.', longevityTip: 'Don\'t chase perfection — enjoy "nearly perfect" instead.' },
        dos: ['Appreciate and enjoy the complementarity', 'Collaboratively solve the gap area', 'Accept differences as personality, not flaws'],
        donts: ['Compare the relationship unfavorably to a Dual', 'Blow one gap into a wholesale rejection', 'Demand total understanding from your partner'],
        concreteTip: 'Example: 80% of the time together feels effortless, but the remaining 20% has an "Hmm?" mismatch. Maybe emotional support is spot-on while practical coordination is slightly off. Whether you can accept that 20% is the key.',
        faq: [
            { question: 'How does Semi-Dual differ from Dual?', answer: 'Duals complement all four functions perfectly; Semi-Duals align on three but misalign on one. It feels like "almost perfect, just one step short."' },
        ],
    },
    Illusionary: {
        type: 'Illusionary',
        name: 'Illusionary',
        nameEn: 'Illusionary',
        stars: 3,
        emoji: '🌈',
        summary: 'Pleasant on the surface, but deeper understanding is elusive — a mirage.',
        overview: 'The Illusionary relationship feels highly attractive at first. You\'re drawn to each other\'s surface traits and quickly think "What a wonderful person."\n\nAs the relationship deepens, however, gaps in core values and communication styles emerge. Like a beautiful mirage, the closer you get, the harder it is to grasp the reality.',
        strengths: ['Great first impressions and easy rapport', 'Mutual politeness and courtesy', 'Short-term interactions are very pleasant'],
        cautions: ['Fundamental misalignments surface as the relationship deepens', 'Hard to read each other\'s true feelings', 'Growing gap between expectations and reality'],
        workCompatibility: { teamDynamics: 'Team atmosphere stays pleasant, but substantive issues tend to get swept under the rug.', roleAdvice: 'Maintain courtesy while intentionally creating spaces for candid discussion.', frictionPoint: '"Nice person, but I have no idea what they\'re thinking" — that mystery becomes stressful.' },
        loveCompatibility: { attraction: 'Drawn by mutual charm, the relationship often starts romantically. You tend to project your "ideal self" onto the other person.', challenge: 'The gap between the idealized partner and the real person becomes painful. "This isn\'t who I thought they were."', longevityTip: 'Don\'t idealize — keep looking at who your partner truly is. Beyond the illusion lies genuine connection.' },
        dos: ['Actively self-disclose and create space for honesty', 'Look beyond surface charm to understand inner depth', 'Approach with realistic expectations'],
        donts: ['Idealize your partner and pile on unrealistic expectations', 'Use surface pleasantry as an excuse to avoid real dialogue', 'Interpret their actions through your own value system'],
        concreteTip: 'Example: After the first lunch you think "What an amazing person!" — but by the third dinner, you start sensing "Wait, they\'re not who I imagined…" A mirage-like relationship.',
        faq: [
            { question: 'How do you succeed in an Illusionary relationship?', answer: 'Don\'t cling to first impressions. Take time to understand the inner person. Accept "who they actually are" rather than "who you want them to be" — that mindset is key.' },
        ],
    },
    Kindred: {
        type: 'Kindred',
        name: 'Kindred',
        nameEn: 'Kindred',
        stars: 3,
        emoji: '🤝',
        summary: 'Shared values but overlapping strengths — allies who may compete.',
        overview: 'The Kindred relationship pairs people with similar worldviews and values. You find it easy to empathize and feel natural affinity.\n\nHowever, overlapping strengths breed competition, and neither can compensate for the other\'s weaknesses. "I understand you, but I can\'t help you" — a frustrating dynamic.',
        strengths: ['Close values make empathy easy', 'Can bond over shared topics', 'Understand each other\'s methods'],
        cautions: ['Overlapping strengths create rivalry', 'Cannot compensate each other\'s weaknesses', 'Limited access to new perspectives'],
        workCompatibility: { teamDynamics: 'You march in the same direction, but identical skill sets make differentiation hard and implicit competition likely.', roleAdvice: 'Deliberately carve out sub-specialties and respect each other\'s territory.', frictionPoint: 'Friction over leadership credit and recognition. Build a fair evaluation framework.' },
        loveCompatibility: { attraction: 'Aligned hobbies and interests make you feel "We click!" — a fun initial connection.', challenge: 'Too similar to keep things fresh; growth stimulation is lacking.', longevityTip: 'Explore new fields together to draw out each other\'s unknown sides and maintain freshness.' },
        dos: ['Acknowledge each other\'s expertise with respect', 'Prioritize cooperation over competition', 'Introduce new experiences together'],
        donts: ['Compare achievements and breed superiority/inferiority', 'Try to outdo each other on the same playing field', 'Neglect outside perspectives'],
        concreteTip: 'Example: Sharing the same leading function (e.g., Ne), you both think "Oh, interesting idea!" — but simultaneously feel "I could do it better." Mutual sharpening and jealousy are separated by a thin line.',
        faq: [
            { question: 'How to avoid competition in Kindred pairs?', answer: 'Divide your specialties clearly. Even with the same abilities, applying them to different domains transforms rivalry into "allies in different fields."' },
        ],
    },
    Business: {
        type: 'Business',
        name: 'Business',
        nameEn: 'Business',
        stars: 3,
        emoji: '💼',
        summary: 'Effective professional collaboration, but emotional connection stays distant.',
        overview: 'The Business relationship, true to its name, works well in professional settings. You respect each other\'s abilities and build a solid working partnership.\n\nHowever, emotional intimacy and personal sharing remain difficult. "Best coworker but awkward friend" is a common feeling.',
        strengths: ['Smooth professional collaboration', 'Mutual respect for professionalism', 'Comfortable maintaining appropriate distance'],
        cautions: ['Hard to build deep emotional bonds', 'Few personal conversation topics', 'Relationship can feel cold or transactional'],
        workCompatibility: { teamDynamics: 'Efficient, professional teamwork is possible. Each person handles their role steadily and delivers consistent results.', roleAdvice: 'Share clear business goals and define contribution areas for maximum efficiency.', frictionPoint: 'Emotional care tends to be neglected. Occasionally schedule casual chats or team-building activities.' },
        loveCompatibility: { attraction: 'Attracted to each other\'s competence and social standing. The relationship tends to be intellectual and polished.', challenge: 'Emotional connection stays thin — "enjoyable together, but hearts don\'t quite touch."', longevityTip: 'Practice intentional emotional disclosure. Show vulnerability. You don\'t have to be perfect.' },
        dos: ['Recognize each other\'s expertise and fairly evaluate contributions', 'Venture into personal topics beyond work', 'Express gratitude and praise in words'],
        donts: ['Confine the relationship to work only', 'Avoid all emotional topics', 'Pursue efficiency at the expense of human warmth'],
        concreteTip: 'Example: Sharing the same creative function (e.g., Ti), your problem-solving approaches align. But your underlying goals differ, creating a strange sensation: "methods match, but destinations diverge."',
        faq: [
            { question: 'Can Business pairs also become close friends?', answer: 'Yes, but it takes deliberate effort. Building emotional bonds through shared non-work experiences (travel, cooking, sports) can evolve the relationship beyond business.' },
        ],
    },
    QuasiIdentity: {
        type: 'QuasiIdentity',
        name: 'Quasi-Identity',
        nameEn: 'Quasi-Identity',
        stars: 2,
        emoji: '🔄',
        summary: 'Seemingly similar yet fundamentally different — misunderstandings abound.',
        overview: 'The Quasi-Identity relationship looks similar on the surface but hides fundamentally different thought processes. "Using the same words but meaning different things" happens constantly.\n\nBecause you expect to understand each other, the disappointment when misalignment surfaces is especially sharp.',
        strengths: ['Easy to find common topics', 'Can understand each other\'s surface behaviors', 'Short-term cooperation works fine'],
        cautions: ['Deep-level fundamental misalignment', 'Over-expectation: "they should understand"', 'Misunderstandings accumulate silently'],
        workCompatibility: { teamDynamics: 'Surface cooperation is possible, but priority differences lead to "Why would you make THAT call?" confusion.', roleAdvice: 'Invest extra time in aligning assumptions and frequently verify you\'re heading the same direction.', frictionPoint: '"Similar but doesn\'t get me" is the biggest source of friction.' },
        loveCompatibility: { attraction: 'Similar vibes create a comforting familiarity that draws you together.', challenge: 'As the relationship deepens, "they were fundamentally different" revelations multiply.', longevityTip: 'Drop the "we\'re similar" assumption and approach each other as entirely separate individuals.' },
        dos: ['Verify assumptions and definitions before communicating', 'Ask for their perspective instead of assuming "they must agree"', 'Treat discovered differences with curiosity, not frustration'],
        donts: ['"Why don\'t you understand?" — don\'t blame the other person', 'Judge based solely on surface similarities', 'Apply your standards to your partner'],
        concreteTip: 'Example: Both value "efficiency," but one means "process efficiency" and the other means "outcome efficiency." Same word, different meanings — "Wait, THAT\'s what you meant?" becomes a recurring theme.',
        faq: [
            { question: 'How does Quasi-Identity differ from Identity?', answer: 'Identity is the same type — perfect match. Quasi-Identity is the E/I (extraversion/introversion) flipped version: surface looks similar, but internal processing is opposite. Like meeting a "mirror-image" of yourself.' },
        ],
    },
    SuperEgo: {
        type: 'SuperEgo',
        name: 'Super-Ego',
        nameEn: 'Super-Ego',
        stars: 2,
        emoji: '⚖️',
        summary: 'Deep mutual respect, but constant tension — hard to relax together.',
        overview: 'In the Super-Ego relationship, you deeply admire the other person and think "I wish I could be like them." They embody your aspirational ideal.\n\nThe flip side: you\'re always trying to present your "best self" around them, never fully relaxing. Extended time together leads to mental fatigue.',
        strengths: ['Deep mutual respect', 'Can learn what you lack from each other', 'Maintain polite, respectful interaction'],
        cautions: ['Constantly performing your best self is tiring', 'Difficult to show your true feelings', 'Hard to build a relaxed relationship'],
        workCompatibility: { teamDynamics: 'High-quality work is possible due to mutual high regard, but psychological tension is ever-present.', roleAdvice: 'Maintain moderate distance and divide by expertise. Avoid close collaboration.', frictionPoint: '"Can\'t afford to lose" pressure makes relaxed cooperation difficult.' },
        loveCompatibility: { attraction: '"I want to be recognized by someone this impressive" — ambition and admiration draw you together. Tends to produce a power-couple dynamic.', challenge: 'Neither can show their true self, making the relationship feel performative. Fear of revealing weakness.', longevityTip: 'Jointly declare: "It\'s OK not to be perfect." The relationship deepens when you show vulnerability first.' },
        dos: ['Express respect for each other verbally', 'Gradually disclose your own weaknesses', 'Allow yourself to be 70% — perfection isn\'t required'],
        donts: ['Keep performing an "impressive" version of yourself', 'Stress over the other\'s evaluation of you', 'View showing weakness as something shameful'],
        concreteTip: 'Example: Watching your partner effortlessly handle your weakest area fills you with both admiration and pressure. "I can\'t fail in front of them" — a tension that never quite lifts.',
        faq: [
            { question: 'How to feel comfortable in a Super-Ego relationship?', answer: 'Explicitly tell each other "it\'s OK not to be perfect." Your partner is likely just as tense as you. Whoever shows vulnerability first makes the relationship easier for both.' },
        ],
    },
    Contrary: {
        type: 'Contrary',
        name: 'Contrary',
        nameEn: 'Contrary',
        stars: 2,
        emoji: '🔥',
        summary: 'Opposing values create short-term sparks and long-term friction.',
        overview: 'The Contrary relationship places opposing value systems head to head. Short-term, you offer each other refreshing stimulation; long-term, fundamental directional differences build friction.\n\n"I can\'t understand how they think, but it\'s interesting" — that\'s this relationship. If both are mature enough to enjoy differences, it becomes fuel for growth.',
        strengths: ['Contrasting viewpoints offer fresh insights', 'Intensely stimulating in the short term', 'Can identify each other\'s blind spots'],
        cautions: ['Long-term friction accumulates', 'Fundamental value clashes are likely', 'Tendency to dismiss each other\'s methods'],
        workCompatibility: { teamDynamics: 'Diverse perspectives enable thorough multi-angle analysis, but reaching consensus takes time.', roleAdvice: 'Assign distinctly different domains and avoid interfering with each other\'s methodology.', frictionPoint: '"Whose approach is right?" leads to unproductive debates. Establish a rule: let results decide.' },
        loveCompatibility: { attraction: 'Strongly drawn to the "opposite appeal" — qualities you don\'t possess.', challenge: 'Daily life is full of "Why would you do THAT?" moments that build stress.', longevityTip: 'Don\'t try to change your partner\'s values. "Different from me, but that\'s OK" — the capacity for acceptance is key.' },
        dos: ['Recognize your partner\'s values as "one valid answer"', 'Aim to laugh about your differences together', 'Increase praise of strengths, decrease criticism of weaknesses'],
        donts: ['Try to convert your partner to your value system', 'Escalate small differences into big problems', 'Repeat "Why don\'t you understand?"'],
        concreteTip: 'Example: Both strong in the same function, but applying it in opposite ways. For instance, both are Ne-strong, but one uses it for innovation, the other for refinement. "Why use it THAT way?" becomes each other\'s catchphrase.',
        faq: [
            { question: 'Should you avoid Contrary relationships?', answer: 'Not at all. Short-term collaboration is intensely stimulating and offers rare perspectives you can\'t get elsewhere. Just be mindful that long-term closeness can be mentally draining — balance is essential.' },
        ],
    },
    Benefit: {
        type: 'Benefit',
        name: 'Benefit',
        nameEn: 'Benefit',
        stars: 2,
        emoji: '🎁',
        summary: 'An asymmetric relationship where one naturally influences the other. Balance matters.',
        overview: 'The Benefit relationship is asymmetric: one person unconsciously holds influence over the other, who receives the benefit. The benefactor naturally leads; the beneficiary gains growth opportunities.\n\nIf this asymmetry goes unnoticed, it can devolve into one-sided dominance and accumulated frustration.',
        strengths: ['The beneficiary gains significant growth opportunities', 'The benefactor can exercise natural leadership', 'Both can learn from each other'],
        cautions: ['The relationship easily becomes imbalanced', 'The beneficiary tends to accumulate stress', 'The benefactor may become unconsciously controlling'],
        workCompatibility: { teamDynamics: 'Functions like a mentor-mentee dynamic with developmental benefits, but equal partnership is difficult.', roleAdvice: 'Acknowledge the asymmetry and create regular forums for flat, open exchange.', frictionPoint: 'The benefactor may unconsciously assume compliance, suppressing the beneficiary\'s autonomy.' },
        loveCompatibility: { attraction: 'The beneficiary is drawn to the benefactor\'s charisma and warmth.', challenge: 'When the beneficiary starts feeling confined by the inequality, the relationship\'s longevity is tested.', longevityTip: 'Break the fixed "teacher / student" dynamic. Find domains where each person can be the expert and build mutual respect.' },
        dos: ['Recognize the asymmetry and actively work to balance it', 'Incorporate the beneficiary\'s opinions and proposals', 'Cheer for each other\'s growth'],
        donts: ['Let one person always lead while the other follows', 'Suppress the beneficiary\'s independence', 'Exploit the asymmetry for control'],
        concreteTip: 'Example: When the benefactor shares a project vision, the beneficiary is naturally inspired: "Oh, I never saw it that way." But influence barely flows in reverse — the beneficiary\'s proposals tend to be overlooked.',
        faq: [
            { question: 'Who is the "benefactor" in a Benefit relationship?', answer: 'In Socionics, the Benefactor\'s leading function aligns with the Beneficiary\'s activating function. The Benefactor\'s natural behavior unconsciously energizes the Beneficiary.' },
            { question: 'How to balance a Benefit relationship?', answer: 'Acknowledge the asymmetry, then intentionally create "reverse mentor" situations — have the benefactor seek guidance in areas where the beneficiary excels.' },
        ],
        directionNote: 'This relationship is asymmetric. The Benefactor and Beneficiary experience it very differently. The Benefactor naturally leads, while the Beneficiary is influenced but finds it hard to push back — a structural imbalance.',
    },
    Supervision: {
        type: 'Supervision',
        name: 'Supervision',
        nameEn: 'Supervision',
        stars: 1,
        emoji: '👁️',
        summary: 'Unconsciously hitting each other\'s weak spots — a high-tension dynamic.',
        overview: 'The Supervision relationship creates a tension where one person\'s natural behavior inadvertently targets the other\'s deepest vulnerability. There\'s no malicious intent, yet the effect is intensely stressful.\n\nThe supervised party constantly feels "watched" and can\'t relax. Awareness of each role and careful distance management are essential.',
        strengths: ['Can objectively identify each other\'s weaknesses', 'Harsh but growth-promoting feedback', 'Motivates weakness mitigation'],
        cautions: ['Extreme stress on the supervised party', 'Unconscious criticism damages the relationship', 'Constructive dynamics are hard to build'],
        workCompatibility: { teamDynamics: 'Can drive performance improvement but at a high psychological cost. Not suited for long-term close collaboration.', roleAdvice: 'Avoid direct hierarchical pairing. Indirect cooperation across separate teams is safer.', frictionPoint: 'A casual remark from the supervisor can feel like a knife to the supervised. Word choice requires extreme care.' },
        loveCompatibility: { attraction: 'Drawn to the other\'s strength while simultaneously feeling nervous about getting closer — a complex mix.', challenge: 'The supervised party stays tense and can\'t establish an equal footing.', longevityTip: 'Treat each other\'s weak spots not as "attack vectors" but as "zones to protect." Kindness is the ultimate weapon.' },
        dos: ['Knowing the other\'s vulnerability, choose to be intentionally gentle', 'Dramatically increase praise vs. criticism ratio', 'Create an environment where the other can relax'],
        donts: ['Repeatedly, even unconsciously, target each other\'s weak points', 'Dismiss it with "Don\'t be so sensitive"', 'Adopt a domineering attitude'],
        concreteTip: 'Example: During a presentation, the supervisor casually notes "Your logic is weak here." That offhand remark strikes the supervised party\'s most vulnerable spot like a knife. Zero malice, deep wound.',
        faq: [
            { question: 'Why is the Supervision relationship so tense?', answer: 'The supervisor\'s leading function directly hits the supervised party\'s weakest 4th function (vulnerable function). The supervisor\'s natural behavior becomes the supervised party\'s worst-case scenario experience.' },
            { question: 'How to work with a Supervision partner?', answer: 'Avoid direct reporting lines. Working toward the same goal on separate teams at arm\'s length is ideal. If unavoidable, introduce a third-party facilitator as a buffer.' },
        ],
        directionNote: 'This relationship is asymmetric. The Supervisor\'s natural behavior targets the Supervisee\'s weakest function. The Supervisor often doesn\'t notice the impact, while the Supervisee is under constant strain — a structural imbalance.',
    },
    Conflict: {
        type: 'Conflict',
        name: 'Conflict',
        nameEn: 'Conflict',
        stars: 1,
        emoji: '⚔️',
        summary: 'The most challenging match. Fundamentally incompatible values.',
        overview: 'The Conflict relationship is considered the most difficult pairing in Socionics. Each person\'s strengths are perceived as irritating stimuli by the other; simply being yourself bothers the other person.\n\nYet this relationship can also be the "greatest catalyst for growth." Confronting the polar opposite of your values can profoundly expand your capacity as a human being.',
        strengths: ['Forced exposure to absent perspectives drives growth', 'Opportunity to expand your human capacity', 'Bonds forged through overcoming difficulty are extremely strong'],
        cautions: ['Just being yourself makes the other uncomfortable', 'Cannot understand each other\'s operating principles', 'Maintaining the relationship requires enormous energy'],
        workCompatibility: { teamDynamics: 'Fundamentally different approaches make consensus nearly impossible. However, with third-party facilitation, revolutionary outcomes are possible.', roleAdvice: 'Minimize direct collaboration. Realistically, work toward the same goal via separate approaches.', frictionPoint: 'Almost everything is a friction point. Communication itself is stressful. A mediator is indispensable.' },
        loveCompatibility: { attraction: 'Drawn by curiosity to a completely alien value system — it feels like "an adventure into the unknown."', challenge: '"Why would you do THAT?" permeates every daily routine — meals, conversations, decisions — none of it aligns.', longevityTip: 'The only rule: don\'t try to change each other. "I can\'t understand, but I still want to be together" requires genuine resolve. Think of it as training.' },
        dos: ['Accept that the other is a fundamentally different being', 'Share each other\'s "landmines" in advance and work to avoid them', 'Actively use third-party mediation'],
        donts: ['Try to force your framework on the other person', 'Impose "That\'s just common sense" — your normal is their abnormal', 'Blame conflicts on the other\'s personality'],
        concreteTip: 'Example: One says "Let\'s grasp the big picture first" while the other insists "Let\'s nail the details first." Both are right, yet they completely fail to sync. A third party suggests "Let\'s alternate" — only then do they move forward.',
        faq: [
            { question: 'Can Conflict pairs build a good relationship?', answer: 'Difficult, but not impossible. If both are mature enough to view differences as "weapons I lack" rather than "flaws," this becomes the relationship that expands your humanity the most. Third-party mediation is always helpful.' },
            { question: 'Why is the Conflict relationship the hardest?', answer: 'Each person\'s leading function corresponds to the other\'s 4th function (weakest), and each creative function corresponds to the other\'s 3rd function (insecure area). Simply being yourself creates comprehensive stress for the other person.' },
        ],
    },
};
